extend = "common.toml"

[config]
load_script = "wget -nc https://raw.githubusercontent.com/cpg314/cargo-make-template/v0.1.0/common.toml"

[tasks.docker]
dependencies = ["build"]
command = "docker"
args = ["build", "-t", "checkalot:${CARGO_MAKE_PROJECT_VERSION}", "."]

[tasks.docker-push]
dependencies = ["docker"]
script = '''
#!/usr/bin/env bash
set -euo pipefail
DEST=ghcr.io/cpg314/checkalot:${CARGO_MAKE_PROJECT_VERSION} 
docker tag checkalot:${CARGO_MAKE_PROJECT_VERSION} $DEST
docker push $DEST
'''
